CREATE TABLE tabulated_functions
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255),
    factory_type VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_tabulated_functions PRIMARY KEY (id)
);
CREATE TABLE points
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    x           DOUBLE PRECISION                        NOT NULL,
    y           DOUBLE PRECISION                        NOT NULL,
    function_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_points PRIMARY KEY (id)
);

ALTER TABLE points
    ADD CONSTRAINT FK_POINTS_ON_FUNCTION FOREIGN KEY (function_id) REFERENCES tabulated_functions (id);